services:
  reverse-proxy:
    image: "reverse-proxy"
    container_name: "reverse-proxy"
    restart: "always"
    networks: 
      - "net"
    ports:
      - "5001:6000"
    depends_on:
      - "backend-one"
      - "backend-two"
  backend-one:
    image: "backend-one"
    container_name: "backend-one"
    networks: 
      - "net"
  backend-two:
    image: "backend-two"
    container_name: "backend-two"
    networks: 
      - "net"

networks:
  net:
    external: true
