apiVersion: v1
kind: Namespace 
metadata:
  name: spike-space
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spike-space
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: reverse-proxy
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spike-space
  name: backend-one
spec:
  selector:
    matchLabels:
      app: backend-one
  template:
    metadata:
      labels:
        app: backend-one
    spec:
      containers:
        - name: backend-one
          image: backend-one
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: spike-space
  name: backend-one-service
spec:
  selector:
    app: backend-one
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spike-space
  name: backend-two
spec:
  selector:
    matchLabels:
      app: backend-two
  template:
    metadata:
      labels:
        app: backend-two
    spec:
      containers:
        - name: backend-two
          image: backend-two
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spike-space
  name: keycloak-auth
spec:
  selector:
    matchLabels:
      app: keycloak-auth
  template:
    metadata:
      labels:
        app: keycloak-auth
    spec:
      containers:
        - name: keycloak-auth
          image: keycloak-auth
          imagePullPolicy: Never
          ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: spike-space
  name: backend-two-service
spec:
  selector:
    app: backend-two
  type: ClusterIP
  ports:
    - protocol: TCP
      name: apis
      port: 8080
    - protocol: TCP
      port: 8081
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  namespace: spike-space
  name: proxy-service
spec:
  selector:
    app: reverse-proxy
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  namespace: spike-space
  name: keycloak-auth
spec:
  selector:
    app: keycloak-auth
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
