version: '1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9080:8080
    depends_on:
      - db
    environment:
      - "KC_HEALTH_ENABLED=true"
      - "KC_METRICS_ENABLED=true"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://db:5432/keycloak"
      - "KC_DB_USERNAME=postgres"
      - "KC_DB_PASSWORD=postgres"
      - "KC_HOSTNAME=localhost"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    command: start-dev --log-level=INFO
    volumes:
      - ./custom-event-listener.jar://opt/keycloak/providers/custom-event-listener.jar
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB: resume
    ports:
      - 5443:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
