events {}

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;
	server {
		listen 5005;
		listen [::]:5005;
		server_name _;
		
		location / {
			proxy_pass 		http://backend-one.flycast:80;
			proxy_set_header 	X-Forwarded-Host 	$http_host;
			proxy_ssl_name 		$host;
			proxy_ssl_server_name 	on;
		}
		
		location /auth/realms {
			proxy_pass 				http://spike-keycloak.flycast:80/auth/realms;
			proxy_set_header X-Real-IP 		$remote_addr;
        		proxy_set_header X-Forwarded-For 	$proxy_add_x_forwarded_for;
        		proxy_set_header X-Forwarded-Proto 	$scheme;
        		proxy_set_header X-Forwarded-Host 	spike-proxy.fly.dev/auth;
			proxy_set_header X-Forwarded-Port 	8080;
                    	add_header Set-Cookie 			$http_cookie;
		}
		
		location /auth/resources {
			proxy_pass 				http://spike-keycloak.flycast:80/auth/resources;
			proxy_set_header X-Real-IP 		$remote_addr;
        		proxy_set_header X-Forwarded-For 	$proxy_add_x_forwarded_for;
        		proxy_set_header X-Forwarded-Proto 	$scheme;
        		proxy_set_header X-Forwarded-Host 	spike-proxy.fly.dev/auth;
			proxy_set_header X-Forwarded-Port 	8080;
                    	add_header Set-Cookie 			$http_cookie;
		}
	}
}
