FROM eclipse-temurin:21-jre
ENV MICRONAUT_ENVIRONMENTS=fly
WORKDIR /home/app
COPY --link build/docker/main/layers/libs /home/app/libs
COPY --link build/docker/main/layers/app /home/app/
COPY --link build/docker/main/layers/resources /home/app/resources
EXPOSE 8080
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
