version: '1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - 9080:9080
      - 9100:9000
    depends_on:
      - db
    environment:
      - "KC_HEALTH_ENABLED=true"
      - "KC_METRICS_ENABLED=true"
      - "KC_DB=postgres"
#      - "KC_DB_URL=jdbc:postgresql://localhost:5433/keycloak"
      - "KC_DB_URL=jdbc:postgresql://db:5432/keycloak"
      - "KC_DB_USERNAME=postgres"
      - "KC_DB_PASSWORD=postgres"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_HOSTNAME_DEBUG=true"
#      - "KC_PROXY_ADDRESS_FORWARDING=true"
      - "KC_HOSTNAME_STRICT=false"
      - "KC_HTTP_PORT=9080"
    command: start-dev --import-realm --http-enabled true
    volumes:
      - ./sampleRealm.json:/opt/keycloak/data/import/sampleRealm.json
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
#    network_mode: "host"
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB: resume
    ports:
      - 5433:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    name: proxy-network
  service-network:
    driver: bridge
    name: service-network
