micronaut:
  server:
    cors:
      enabled: true
  security:
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://keycloak-auth:8080/auth/realms/spike-realm/protocol/openid-connect/certs

grpc:
  channels:
    greeter:
      address: http://backend-two:8081
      plaintext: true
  client:
    max-retry-attempts: 5

logger:
  levels:
    io.micronaut.security: DEBUG