micronaut:
  application:
    name: spike-client-one
  http:
    services:
      spike-client-two:
        url: http://spike-two:8080
  server:
    port: 8080
  security:
    oauth2:
      clients:
        keycloak:
          client-id: spike-client-one
          client-secret: secret-one
          openid:
            issuer: http://keycloak:9080/realms/spike-realm
        keycloak-client:
          client-id: spike-client-one
          client-secret: secret-one
          grant-type: client_credentials
          token:
            url: http://keycloak:9080/realms/spike-realm/protocol/openid-connect/token
            auth-method: client_secret_post
          client-credentials:
            service-id-regex: spike-client-two
          openid:
            issuer: http://keycloak:9080/realms/spike-realm/

    endpoints:
      logout:
        get-allowed: true
logger:
  levels:
    io.micronaut.security: DEBUG
    io.micronaut.http.client: DEBUG
