events {}

http {
	server {
		listen 6000;
		server_name localhost;
		location / {
			proxy_pass http://backend-one:5000;
		}
		
		location = /request {
			proxy_pass http://backend-one:5000/request;
		}
		
		location ~ /params {
			proxy_pass http://backend-one:5000;
		}
	}
}
