micronaut:
  application:
    name: spike-client-one
  http:
    services:
      spike-client-two:
        url: http://spike-two.psn.local
  server:
    port: 8081
  security:
    oauth2:
      clients:
        keycloak:
          client-id: spike-client-one
          client-secret: giqoOPMxVdlwitldmjSy4KviPDLImbjo
          grant-type: client_credentials
          token:
            url: http://keycloak.psn.local/realms/spike-realm/protocol/openid-connect/token
            auth-method: client_secret_post
          client-credentials:
            service-id-regex: spike-client-two
          openid:
            issuer: http://keycloak.psn.local/realms/spike-realm/
    endpoints:
      logout:
        get-allowed: true
logger:
  levels:
    io.micronaut.security: DEBUG
    io.micronaut.http.client: DEBUG
